name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Loop_Exercise tests
        run: |
          pytest "Loop_Exercise/tests"

      - name: Run Python Basic Exercise tests
        run: |
          pytest "Python Basic Exercise/tests"

      - name: Run Functions Exercise tests
        run: |
          pytest "Functions Exercise/tests"

      - name: Run Python_Input_and_Output_Exercise tests
        run: |
          pytest "Python_Input_and_Output_Exercise/tests"

      - name: Run String Exercise tests
        run: |
          pytest "String Exercise/tests"

